image: nixos/latest
sources:
  - https://git.sr.ht/~moody/sakuya
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
tasks:
  - build: |
      cd sakuya
      # Can't build oot without the rom
      sed -i '/shipwright/d' configuration.nix
      nix build '.#nixosConfigurations.sakuya.config.system.build.toplevel'
